
name: Python
on: [ push ]
jobs:
    test-I:
        name: 'Perform REST API'
        runs-on: ubuntu-latest
        steps:
            - name: 'Call API'
              uses: indiesdev/curl@v1
              id: api
              with:
                url: https://reqres.in/api/users
                method: 'POST'
                accept: 201
                body: '{ "name": "breeze",  "job": "devops" }'

            - name: My backup step
              if: False
              uses: casperdcl/deploy-pypi@v1
              with:
                password: ${{ secrets.pypi_token }}
                build: true
