
name: Python
on:
  push:


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: casperdcl/deploy-pypi@v1
        with:
          password: ${{ secrets.pypi_token }}
          build: true

  buildII:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      if: 1 == 1
      - run: echo "ok"
