#
#
#name: Check Deployment and versions
#
#on:
#  push:
#
##        hash=${{ GITHUB.SHA }}
#
#jobs:
#  check-tag-branch:
#    runs-on: ubuntu-latest
#    steps:
#    - name: get tag commit hash
#      id: tag-commit-hash
#      run: |
#        hash=${{ GITHUB.SHA }}
#        echo "::set-output name=tag-hash::${hash}"
#
##https://api.github.com/repos/flooie/sampleproject/tags

uses: satak/webrequest-action@master
with:
  url: https://api.github.com/repos/flooie/sampleproject/tags
  method: GET
  run: |
    $output = '${{ steps.webhook.outputs.output }}' | ConvertFrom-Json
    echo "$output"