name: Sample Testing

on: 
  [push]

jobs:
  one:
    runs-on: ubuntu-latest
    steps:
      - name: Test Trigger
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"
        
      - name: Test Trigger II
        env:
          GT: ${{ toJson(github) }}
        run: echo "${{ toJson(github) }}"
