name: PyPI
on:
  push:
    tags:
      - v*.*.*
jobs:
  PyPI:
    steps:
      - uses: actions/checkout@v2
      - uses: casperdcl/deploy-pypi@v1
        with:
          password: ${{ secrets.pypi_token }}
          build: true
