name: Sample Testing

on: 
  [push]

jobs:
  one:
    runs-on: ubuntu-latest
    steps:
      - name: Test Trigger
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"
        
      - name: Test Trigger II
        env:
          COMMIT_MESSAGE: ${{ github.event.head_commit.message }}
        run: echo "${{ github.event.head_commit.message }}"

      - name: Test Trigger II
      - if: contains(env.COMMIT_MESSAGE, 'SomeString')
        run: echo "The commit message is some string"
