name: Sample Testing

on: 
  [push]

jobs:
  one:
    runs-on: ubuntu-latest
    steps:
      - name: Test Trigger I
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"
        
      - name: Test Trigger II
        env:
          COMMIT_MESSAGE: ${{ github.event.head_commit.message }}
        run: echo "$COMMIT_MESSAGE"

      - name: Test Trigger III
        env:
          COMMIT_MESSAGE: ${{ github.event.head_commit.message }}
        if: contains(env.COMMIT_MESSAGE, 'SomeString')
        run: echo "The commit message is some string SomeString"
        if: !contains(env.COMMIT_MESSAGE, 'SomeString')
        run: echo "This was a normal commit message"
