name: Python
on:
  push:

#      - uses: actions/checkout@v2
#      - uses: casperdcl/deploy-pypi@v1
#        with:
#          password: ${{ secrets.pypi_token }}
#          build: true

jobs:
  py:
    runs-on: ubuntu-latest
    steps:
      - name: Check tags on this PR
        shell: python
        id: vars
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: |
          import os, json, urllib

          context = json.loads(os.environ['GITHUB_CONTEXT'])
          tag_url = context['event']['repository']['tags_url']
          tags = json.loads(urllib.urlopen(tag_url).read())

          tagged_sha1 = tags[0]['commit']['sha']
          tag_name = tags[0]['name']

          default = context['event']['repository']['default_branch']
          branch = context['ref']

          if default in branch:
            ids = [x['id'] for x in context['event']['commits']]
            if tagged_sha1 in ids:
              print("tagged ID was in the most recent PR and should be sent to PyPI")
              print("Submit", tag_name, " to PyPI")

      - name: Create Pull Request
        run: echo "PR_TITLE=[Test] Add report file $(date +%d-%m-%Y)" >> $GITHUB_ENV

      - name: Print PRTITLE
        shell: python
        run: |
          import os
          PR_TITLE = os.environ['PR_TITLE']
          print(PR_TITLE)


#        run: |
#          import os, json, urllib
#          print("OKOOKKOOK")
#          print(os.environ['steps'])

#      - name: Build PYPI
#        run: |
#          import os, json, urllib
#
#
#        shell: python

#  build:
#    runs-on: ubuntu-latest
#    steps:
#      - uses: actions/checkout@v2
#      - uses: casperdcl/deploy-pypi@v1
#        with:
#          password: ${{ secrets.pypi_token }}
#          build: true


#  pypi:
#    name: Slack
#    needs: publish # set needs only last job except this job
#    runs-on: ubuntu-latest
#    if: always() # set always
#    steps:
#