name: Python
on:
  push:

jobs:
  py:
    runs-on: ubuntu-latest
    steps:
      - name: Read package.json
        run: |
          import os, glob
          print(os)
          print(glob.glob("*"))


      - name: Display the path
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: |
          import os, json, urllib
          context = json.loads(os.environ['GITHUB_CONTEXT'])
          tags = json.loads(urllib.urlopen("https://api.github.com/repos/flooie/sampleproject/tags").read())
          tagged_sha1 = tags[0]['commit']['sha']
          tag_name = tags[0]['name']
          default = context['event']['repository']['default_branch']
          branch = context['ref']
          if default in branch:
            ids = [x['id'] for x in context['event']['commits']]
            if tagged_sha1 in ids:
              print("tagged ID was in the most recent PR and should be sent to PyPI")
              print("Submit", tag_name, " to PyPI")

        shell: python



#so its only on push