name: Python
on:
  push:

jobs:
  py:
    runs-on: ubuntu-latest
    steps:
      - name: Display the path
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: |
          import os, json, urllib
          context = json.loads(os.environ['GITHUB_CONTEXT'])
          print(context)
          if context["ref"] == "refs/heads/newmaster":
            contents = urllib.urlopen("https://example.com/foo/bar").read()
            print(contents)

        shell: python
