name: Python
on:
  push:

jobs:
  py:
    runs-on: ubuntu-latest
    steps:
      - name: Display the path
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: |
          import os, json, urllib
          context = json.loads(os.environ['GITHUB_CONTEXT'])
          current_sha1 = context["sha"]
          tags = urllib.urlopen("https://api.github.com/repos/flooie/sampleproject/tags").read()
          j_tags = json.loads(tags)
          tagged_sha1 = j_tags[0]['commit']['sha']
          if tagged_sha1 == current_sha1:
            print(tagged_sha1, "==", current_sha1)
            print("This branch is tagged aaaaaand is the branch we want RUN PYPI...")
          else:
            tags = urllib.urlopen("https://api.github.com/repos/flooie/sampleproject/tags").read()
            j_tags = json.loads(tags)
            print(j_tags[0]['name'])
            print(j_tags[0]['commit']['sha'])

            print(context["ref"])


        shell: python
