name: Python
on:
  push:

jobs:
  py:
    runs-on: ubuntu-latest
    steps:
      - name: Check tags on this PR
        shell: python
        id: vars
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: |
          import os, json, urllib, subprocess

          context = json.loads(os.environ['GITHUB_CONTEXT'])
          tag_url = context['event']['repository']['tags_url']
          tags = json.loads(urllib.urlopen(tag_url).read())

          tagged_sha1 = tags[0]['commit']['sha']
          tag_name = tags[0]['name']

          default = context['event']['repository']['default_branch']
          branch = context['ref']

          if default in branch:
            ids = [x['id'] for x in context['event']['commits']]
            if tagged_sha1 in ids:
              print("tagged ID was in the most recent PR and should be sent to PyPI")
              print("Submit", tag_name, " to PyPI")
              subprocess.call('echo ::set-output name=continue::True', shell=True)
          else:
            subprocess.call('echo ::set-output name=continue::False', shell=True)

      - name: Generate PYPI
      - uses: actions/checkout@v2
      - uses: casperdcl/deploy-pypi@v1
          with:
            password: ${{ secrets.pypi_token }}
            build: true
        if: steps.vars.outputs.continue == 'True'
