name: Python
on:
  push:

jobs:
  py:
    runs-on: ubuntu-latest
    steps:
      - name: Display the path
        run: |
          import os
          print(os.environ['PATH'])
          pip install requests
          print(requests)
        shell: python
