name: Python
on:
  push:

jobs:
  py:
    runs-on: ubuntu-latest
    steps:
      - name: Display the path
        env:
          COMMIT_MSG: ${{ github.event.head_commit.message }}
          BRANCH: ${{ github.ref }}
          GITHUB_CONTEXT: ${{ toJson(github) }}
          ACTION: ${{ toJson(github.action) }}
          MERGE_STATUS: ${{ toJson(github.pull_request.merged) }}

        run: |
          import os
          import json
          import urllib.request

          context = json.loads(os.environ['GITHUB_CONTEXT'])

          if context["ref"] == "refs/heads/newmaster":
            print("OK")
            contents = urllib.request.urlopen("http://example.com/foo/bar").read()
            print(contents)



        shell: python
