name: Python
on:
  push:

jobs:
  py:
    runs-on: ubuntu-latest
    steps:
      - name: Display the path
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: |
          import os, json, urllib
          context = json.loads(os.environ['GITHUB_CONTEXT'])
          current_sha1 = context["sha"]
          tags = json.loads(urllib.urlopen("https://api.github.com/repos/flooie/sampleproject/tags").read())
          print(tags)
          tagged_sha1 = tags[0]['commit']['sha']
          tag_name = tags[0]['commit']['name']
          print(tag_name)


          print(context['event'])

          if tagged_sha1 == current_sha1:
            print(tagged_sha1, "==", current_sha1)
            print("This branch is tagged aaaaaand is the branch we want RUN PYPI...")
          else:
            print(tags)
            print(tagged_sha1)
            print("this push was not tagged so - no need to pypi it")
            print(context["ref"])

          print(context['ref'])
          print(context['event']['repository']['default_branch'])

          ids = [x['id'] for x in context['event']['commits']]
          if tagged_sha1 in ids:
            print("tagged ID was in the most recent PR and should be sent to PyPI")

#          for commit in context['event']['commits']:
#            print(commit['id'], "<-------")
#            if commit['id'] == tagged_sha1:
#              print("tagged ID was in the most recent PR and should be sent to PyPI")
#              break

        shell: python


#so its only on push