name: Tagged PR Merger

on:
  push:
    tags:
      - v*.*.*

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Pull request merged
      if: github.action == 'closed' && github.pull_request.merged == 'true'
      run: echo merged
